name: test2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  QT_VERSIONS: '["5.15.1"]'
  IOS_DEPLOYMENT_ARCHITECTURE: '["arm64", "x86_64"]'

jobs:
  build-sdk:

    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        qt-version: ${{ fromJSON( env.QT_VERSIONS ) }}
        ios-deployment-architecture: ${{ fromJSON( env.IOS_DEPLOYMENT_ARCHITECTURE ) }}
        include:
          - qt-version: '5.15.1'
            ios-deployment-target: '12.0'

    outputs:
      matrix: ${{ toJSON(strategy) }}
            
    steps:
      - run: echo ${XXX}
        env:
          XXX: ${{ strategy }}
      
  test2:
    needs: build-sdk
    runs-on: macOS-latest
    steps:
      - run: echo ${XXX}
        env:
          XXX: ${{ needs.build-sdk.outputs.matrix }}
      
  publish-sdk:
    needs: build-sdk
    runs-on: macOS-latest

    strategy:
      matrix: 
        qt-version: ${{ fromJSON( env.QT_VERSIONS ) }}
        ios-deployment-architecture: ${{ fromJSON( env.IOS_DEPLOYMENT_ARCHITECTURE ) }}
        include:
          - qt-version: '5.15.1'
            ios-deployment-target: '12.0'      
      
    steps:
      - run: echo ${QTVERSION}
        env:
          QTVERSION: ${{ matrix.qt-version }}
