name: test2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build-sdk:

    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        qt-version: ['5.15.1']
        ios-deployment-architecture: ['arm64', 'x86_64']
        include:
          - qt-version: '5.15.1'
            ios-deployment-target: '12.0'
            
    steps:
      - uses: actions/checkout@v2
      
  publish-sdk:
    needs: build-sdk
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix: ${{ jobs.build-sdk.strategy.matrix }}

    steps:
      - run: echo ${QTVERSION}
        env:
          QTVERSION: ${{ matrix.qt-version }}
